### ISSUE TITLE
Running GUI-Task requires jmx-File to be present

### ISSUE THREAD

**Issue by mathze** [qualersoft/jmeter-gradle-plugin#20]
**Describe the bug**
When I try to run a JMeterGuiTask without giving a jmx-File the task fails.
For GUI-Task it should be ok to have no jmx-File, meaning it starts empty but with all set configurations (plugins, properties, etc.)

**To Reproduce**
1. create a new gradle-project applying the plugin
2. create a JMeterGuiTask with no config (or at least with jmxFile unset)
```
plugins {
  id("de.qualersoft.jmeter") version "2.0.0"
}
// ...
tasks {
  register<JMeterGuiTask>("emptyGui")
}
```
3. ⚠️execute the task

**Expected behavior**
The JMeter UI should start with an empty testplan

**Data/Screenshots**
The execution fails with following error
```
A problem was found with the configuration of task ':emptyGui' (type 'JMeterGuiTask').
  - In plugin 'de.qualersoft.jmeter' type 'de.qualersoft.jmeter.gradleplugin.task.JMeterGuiTask' property 'sourceFile$jmeter_gradle_plugin' doesn't have a configured value.
```

**System (please complete the following information):**
- OS: Windows
- OS-Version: 11 - 21H2 (Build 22000.194)
- Gradle-Version: 7.2
- Plugin-Version: 2.0.0

**Comment by kheerthi** [comment]
Is this issue verified resolved. I am getting the same error.

**Comment by mathze** [comment]
Yes it is. It was introduced in v2.1.0. To be 100% sure, I've actually reconfirmed it with v2.4.0.
