### ISSUE TITLE
`jmRun` should fail the build on any JMeter sampler errors

### ISSUE THREAD

**Issue by DKroot** [qualersoft/jmeter-gradle-plugin#42]
**Describe the bug**
When JMeter reports any number of errors, the build should error out.

**To Reproduce**
1. Introduce an erroneous sample into a test suite
2. `gradle jmRun`

**Expected behavior**
Build should fail e,g, on the following results:
```
executed samples =     75 in 00:00:11 =    6.6/s Avg:   168 Min:     0 Max:  1448 Err:    12 (16.00%)
```

**System (please complete the following information):**
- OS: macOS
- OS-Version: 11.6.5
- Gradle-Version: 7.4.2
- Plugin-Version: 2.2.2

**Comment by mathze** [comment]
@DKroot,
this is nothing about the plugin but about JMeter itself. JMeter return 0 even if a sampler error occurred.
If JMeter would exit with an non-zero result code than the execution would automatically fail as required.

There are some posts around this in the web to achieve what you want. But that's something you have to do in your JMeter script.

**Comment by DKroot** [comment]
I implemented a workaround. But, I migrated from `com.patdouble.jmeter-gradle-plugin` and it was failing builds out-of-the-box without me having to anything in my JMeter suite. This behavior was a regression after the migration. Other than that, the migration was easy.

**Comment by DKroot** [comment]
If anybody needs a workaround for this:
1. Dump errors into a CSV in your JMeter suite, e.g. via View Results Tree listener > Log/Display: = Errors only
2.
```Gradle
import de.qualersoft.jmeter.gradleplugin.task.*

final def PERF_TEST_SUITE_FILE_NAME = 'navigation_tests.jmx'

def jmeterTestResultsDir = "${project.buildDir}/test-results/jmeter"

tasks.register('jmFailOnErrors') {
  doLast {
    assert file("${jmeterTestResultsDir}/errors.csv").length() == 0 : 'Some performance test samples failed'
  }
}

tasks.register('jmRun', JMeterRunTask) {
  description 'Executes the performance tests'
  // TBD Consolidate custom `${project.buildDir}/jmeter-report` with the main test results directory
  // Empty `${project.buildDir}/reports/jmeter` is an unused run artifact
  outputs.dirs jmeterTestResultsDir, "${project.buildDir}/jmeter-report", "${project.buildDir}/reports/jmeter"
  outputs.file "${project.buildDir}/logs/jmeter.log"
  jmxFile = PERF_TEST_SUITE_FILE_NAME
  finalizedBy jmFailOnErrors
}
// Always clean otherwise it might be skipped as UP-TO-DATE
// It has to be specified separately from the `jmRun` task definition because `cleanJmRun` is defined simulatenously
jmRun.dependsOn cleanJmRun
```
